from fpdf import FPDF
from datetime import datetime

def clean_text(text):
    """Remove unsupported unicode characters for FPDF"""
    return text.encode("latin-1", "replace").decode("latin-1")

def generate_report(df, lat, lon, hour, weekend, cvi, explanation):

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Arial", "B", 18)
    pdf.cell(0, 10, clean_text("CrimeShield AI Intelligence Report"), ln=True, align="C")
    pdf.ln(5)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 10, clean_text(f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}"), ln=True)
    pdf.ln(5)

    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, clean_text("1. Location Details"), ln=True)
    pdf.set_font("Arial", "", 12)

    location_text = f"""
Latitude: {lat}
Longitude: {lon}
Hour: {hour}
Weekend: {weekend}
"""

    pdf.multi_cell(0, 8, clean_text(location_text))
    pdf.ln(3)

    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, clean_text("2. Crime Vulnerability Assessment"), ln=True)
    pdf.set_font("Arial", "", 12)

    if cvi >= 60:
        risk_level = "High Risk"
    elif cvi >= 30:
        risk_level = "Moderate Risk"
    else:
        risk_level = "Low Risk"

    assessment_text = f"""
Crime Vulnerability Index (CVI): {cvi}/100
Risk Level: {risk_level}

This score is generated using machine learning
patterns from historical crime data.
"""

    pdf.multi_cell(0, 8, clean_text(assessment_text))
    pdf.ln(3)

    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, clean_text("3. AI Intelligence Interpretation"), ln=True)
    pdf.set_font("Arial", "", 12)

    pdf.multi_cell(0, 8, clean_text(explanation))
    pdf.ln(3)

    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, clean_text("4. Recommended Action"), ln=True)
    pdf.set_font("Arial", "", 12)

    if risk_level == "High Risk":
        recommendation = """
Increase police visibility
Deploy surveillance monitoring
Community alert recommended
"""
    elif risk_level == "Moderate Risk":
        recommendation = """
Increase patrol frequency
Monitor peak hours
Community awareness advised
"""
    else:
        recommendation = """
Maintain regular monitoring
No immediate action required
"""

    pdf.multi_cell(0, 8, clean_text(recommendation))

    pdf.ln(5)
    pdf.set_font("Arial", "I", 10)
    footer = """
This report was automatically generated by CrimeShield AI.
"""

    pdf.multi_cell(0, 6, clean_text(footer))

    file_path = "CrimeShield_AI_Intelligence_Report.pdf"
    pdf.output(file_path)


    return file_path
